name: test-and-lint
run-name: test and lint
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        # Check-out repository under GitHub workspace
        # https://github.com/actions/checkout
      - uses: actions/checkout@v2
        # Step's name
      - name: Setup PHP
        # Action gives to setup the PHP environment to test application
        # https://github.com/shivammathur/setup-php
        uses: shivammathur/setup-php@v2
        with:
          # Specify the PHP version
          php-version: '8.1'
      - name: Install
        # Install project
        run: make install
      - name: Install PHP_CodeSniffer globally
        run: composer global require squizlabs/php_codesniffer
      - name: Run linter
        # Run Linter
        run: make lint
